### ISSUE TITLE
An error occured trying to load record details: undefined

### ISSUE THREAD

**Issue by e96194** [capeterson/Grey-Tab#18]
Hi, 

I LOVE this extension, but occasionally get this error: "An error occured trying to load record details: undefined" and it doesn't show me any values. 

Do you know what could cause this? 

Thanks! 

Adam.

**Comment by capeterson** [comment]
Nothing obvious off the top of my head, let me see if I can push a new release with some better (i.e. existent) logging and if that gets some better debug info.

**Comment by e96194** [comment]
Ok great, I'll let you know my results once I have the latest version. Thanks so much!

**Comment by capeterson** [comment]
Sorry to take so long on this - work's been keeping me pretty busy. I finally got some work done on getting a logging implementation in place (feature/logging branch), but it's not ready for release just yet.

**Comment by e96194** [comment]
Hey Chris, no worries at all, I know the feeling as I'm slammed with work too!

Thanks again,

Adam.

**Comment by e96194** [comment]
Hey Chris,

Any news on this one?

Thanks!

Adam.

From: Adam Cooper
Sent: 09 February 2015 09:33 AM
To: 'capeterson/Grey-Tab'
Subject: RE: [Grey-Tab] An error occured trying to load record details: undefined (#18)

Hey Chris, no worries at all, I know the feeling as I'm slammed with work too!

Thanks again,

Adam.

**Comment by e96194** [comment]
Hey Chris,

Did you ever manage to fix this?

Thanks!

Adam.

From: Adam Cooper
Sent: 11 March 2015 01:07 PM
To: 'capeterson/Grey-Tab'
Subject: RE: [Grey-Tab] An error occured trying to load record details: undefined (#18)

Hey Chris,

Any news on this one?

Thanks!

Adam.

From: Adam Cooper
Sent: 09 February 2015 09:33 AM
To: 'capeterson/Grey-Tab'
Subject: RE: [Grey-Tab] An error occured trying to load record details: undefined (#18)

Hey Chris, no worries at all, I know the feeling as I'm slammed with work too!

Thanks again,

Adam.

**Comment by capeterson** [comment]
No fix yet, and the logging is still not done, although reasonably far along, but a co-worker showed me this error today and was kind enough to let me play around with the debugger for a while. Can you open the session info tab and tell me what the "Host" value says? If that's an invalid value then it would likely be the same issue, and I have a good idea how to attack it.

**Comment by e96194** [comment]
Hi Chris,

I've been using this a lot over the past few days and haven’t run into this problem.

If I get it again, I'll check the host value and let you know.

Adam.
