### ISSUE TITLE
Can't obtain Record Details for objects that have lots of fields

### ISSUE THREAD

**Issue by kpeterson85** [capeterson/Grey-Tab#23]
If a user has access to a lot of fields, the query for the record's data can come back with the exception "QUERY_TOO_COMPLICATED: Query is either selecting too many fields or the filter conditions are too complicated.".  The popup in the extension says "undefined" but that is the error behind the scenes.  Could you do multiple requests for the field data, limiting each query to the max number of fields allowed per query, then combine all of the data in the end?  It's frustrating when users can use this great extension feature on certain objects but then can't on others.

**Comment by capeterson** [comment]
Interesting, I always knew this was a theoretical possibility but haven't ever seen or heard of anything big enough to break it. I'll look into adding support for multiple queries and assembling the data on the client side.

Can I ask how many fields your object has where you're seeing this?

**Comment by capeterson** [comment]
Took a stab at this today and I have a branch, `feature/complex-objects` that seems to have this working. I've only done minimal testing though, and may well have broken something for all I know.

Can you try loading it from source (just download the source as a zip off github and load it as an unpacked extension, I can explain more if needed) and let me know if it works for you there?

**Comment by kpeterson85** [comment]
Two of the object types I was previously experiencing the issue on came up fine for me using the zip of the new branch.  Thanks for looking into it!  We'll be excited for when it gets put into the official release.

**Comment by capeterson** [comment]
Cool, thanks for confirming. I need to do some testing and make sure I didn't break anything (TODO: unit tests) before I roll up a release. Thinking end of this month or so, but we'll see how things shake out.
